package database;
// Generated Jul 29, 2020 4:17:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer cid;
     private Product product;
     private User user;
     private Integer qty;
     private int status;
     private Set cartHasInvoices = new HashSet(0);

    public Cart() {
    }

	
    public Cart(Product product, User user, int status) {
        this.product = product;
        this.user = user;
        this.status = status;
    }
    public Cart(Product product, User user, Integer qty, int status, Set cartHasInvoices) {
       this.product = product;
       this.user = user;
       this.qty = qty;
       this.status = status;
       this.cartHasInvoices = cartHasInvoices;
    }
   
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Set getCartHasInvoices() {
        return this.cartHasInvoices;
    }
    
    public void setCartHasInvoices(Set cartHasInvoices) {
        this.cartHasInvoices = cartHasInvoices;
    }




}


