package database;
// Generated Jul 29, 2020 4:17:48 PM by Hibernate Tools 4.3.1



/**
 * Contactus generated by hbm2java
 */
public class Contactus  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String conatctno;
     private String address;

    public Contactus() {
    }

    public Contactus(String email, String conatctno, String address) {
       this.email = email;
       this.conatctno = conatctno;
       this.address = address;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getConatctno() {
        return this.conatctno;
    }
    
    public void setConatctno(String conatctno) {
        this.conatctno = conatctno;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


