package database;
// Generated Jul 29, 2020 4:17:48 PM by Hibernate Tools 4.3.1



/**
 * Editslider generated by hbm2java
 */
public class Editslider  implements java.io.Serializable {


     private int id;
     private String pic;

    public Editslider() {
    }

	
    public Editslider(int id) {
        this.id = id;
    }
    public Editslider(int id, String pic) {
       this.id = id;
       this.pic = pic;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getPic() {
        return this.pic;
    }
    
    public void setPic(String pic) {
        this.pic = pic;
    }




}


