package database;
// Generated Jul 29, 2020 4:17:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer invid;
     private User user;
     private Double total;
     private Integer status;
     private String contact;
     private String address;
     private Set cartHasInvoices = new HashSet(0);

    public Invoice() {
    }

	
    public Invoice(User user) {
        this.user = user;
    }
    public Invoice(User user, Double total, Integer status, String contact, String address, Set cartHasInvoices) {
       this.user = user;
       this.total = total;
       this.status = status;
       this.contact = contact;
       this.address = address;
       this.cartHasInvoices = cartHasInvoices;
    }
   
    public Integer getInvid() {
        return this.invid;
    }
    
    public void setInvid(Integer invid) {
        this.invid = invid;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Set getCartHasInvoices() {
        return this.cartHasInvoices;
    }
    
    public void setCartHasInvoices(Set cartHasInvoices) {
        this.cartHasInvoices = cartHasInvoices;
    }




}


