package database;
// Generated Jul 29, 2020 4:17:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer pid;
     private Brand brand;
     private Type type;
     private String pname;
     private Double price;
     private Integer qty;
     private String image;
     private Integer status;
     private String description;
     private Date expiry;
     private Set carts = new HashSet(0);

    public Product() {
    }

	
    public Product(Brand brand, Type type, String description) {
        this.brand = brand;
        this.type = type;
        this.description = description;
    }
    public Product(Brand brand, Type type, String pname, Double price, Integer qty, String image, Integer status, String description, Date expiry, Set carts) {
       this.brand = brand;
       this.type = type;
       this.pname = pname;
       this.price = price;
       this.qty = qty;
       this.image = image;
       this.status = status;
       this.description = description;
       this.expiry = expiry;
       this.carts = carts;
    }
   
    public Integer getPid() {
        return this.pid;
    }
    
    public void setPid(Integer pid) {
        this.pid = pid;
    }
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }
    public String getPname() {
        return this.pname;
    }
    
    public void setPname(String pname) {
        this.pname = pname;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getExpiry() {
        return this.expiry;
    }
    
    public void setExpiry(Date expiry) {
        this.expiry = expiry;
    }
    public Set getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set carts) {
        this.carts = carts;
    }




}


