package database;
// Generated Jul 29, 2020 4:17:48 PM by Hibernate Tools 4.3.1



/**
 * Suspend generated by hbm2java
 */
public class Suspend  implements java.io.Serializable {


     private int id;
     private String path;
     private String text;
     private Integer status;

    public Suspend() {
    }

	
    public Suspend(int id) {
        this.id = id;
    }
    public Suspend(int id, String path, String text, Integer status) {
       this.id = id;
       this.path = path;
       this.text = text;
       this.status = status;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


