package database;
// Generated Jul 29, 2020 4:17:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String email;
     private String name;
     private String password;
     private String image;
     private int status;
     private Integer code;
     private Set carts = new HashSet(0);
     private Set invoices = new HashSet(0);

    public User() {
    }

	
    public User(String email, int status) {
        this.email = email;
        this.status = status;
    }
    public User(String email, String name, String password, String image, int status, Integer code, Set carts, Set invoices) {
       this.email = email;
       this.name = name;
       this.password = password;
       this.image = image;
       this.status = status;
       this.code = code;
       this.carts = carts;
       this.invoices = invoices;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public Set getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set carts) {
        this.carts = carts;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }




}


